#dist: trusty
dist: xenial
sudo: required
language:
  - minimal
cache:
  apt: true
  directories:
    - $HOME/ccache
services:
  - docker

env:
#  - DISTR=indigo  BASEIMG=osrf/ros:indigo-desktop-full
  - DISTR=kinetic BASEIMG=osrf/ros:kinetic-desktop-full

before_script:
  - mkdir -p $HOME/ccache/${DISTR}/.ccache
  - mv $HOME/ccache/${DISTR}/.ccache .
  # - pwd
  # - ls
  # - echo $HOME
  - docker pull ${BASEIMG}
#  - docker build -f Dockerfile.kinetic_hrpsys --tag start-jsk/hrpsys_choreonoid:kinetic .

script:
  - docker build -f Dockerfile.${DISTR} --tag start-jsk/rtmros_choreonoid:${DISTR} .

before_cache:
  # - ls
  - docker create --name ${DISTR} start-jsk/rtmros_choreonoid:${DISTR}
  # - docker ps -a
  - docker cp ${DISTR}:/root/.ccache $HOME/ccache/${DISTR}/

# jobs:
#   include:
#     - stage: preinstall_hrpsys
#       script: docker build -f Dockerfile.kinetic_hrpsys --tag start-jsk/hrpsys_choreonoid:kinetic .
#     - stage: main
#       script: docker build -f Dockerfile.kinetic_main   --tag start-jsk/rtmros_choreonoid:kinetic .
